# Generated by Django 3.2.5 on 2021-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.FilePathField(path='/players/img'),
        ),
    ]
