# Generated by Django 3.2.5 on 2021-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
